apiVersion: v1
kind: Secret
metadata:
  name: platform-lab-secret
  namespace: platform-lab
type: Opaque
stringData:
  POSTGRES_USER: app_user
  POSTGRES_PASSWORD: app_password
  DATABASE_URL: postgresql://app_user:app_password@postgres-service:5432/platform_lab