apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-lab-config
data:
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_HOST: {{ .Values.postgres.service.name | quote }}
  POSTGRES_PORT: {{ .Values.postgres.service.port | quote }}