apiVersion: v1
kind: Secret
metadata:
  name: platform-lab-secret
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%v/%s" .Values.postgres.username .Values.postgres.password .Values.postgres.service.name .Values.postgres.service.port .Values.postgres.database | quote }}