backend:
  replicaCount: 2
  image:
    repository: europe-west3-docker.pkg.dev/gke-sre-500509/platform-lab/platform-lab-backend
    tag: jenkins-21-f0197c2
    pullPolicy: IfNotPresent

frontend:
  replicaCount: 2
  image:
    repository: europe-west3-docker.pkg.dev/gke-sre-500509/platform-lab/platform-lab-frontend
    tag: jenkins-21-f0197c2
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer

ingress:
  enabled: false
  host: platform-lab.example.com

monitoring:
  serviceMonitor:
    enabled: true
    interval: 15s
